apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-deployment
  labels:
    app: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab
  template:
    metadata:
      labels:
        app: lab
    spec:
      containers:
      - name: labdb
        image: slavautkin/mysql:5.7
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
        env:
        - name: MYSQL_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: lab-sec
              key: username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lab-sec
              key: password
---

apiVersion: v1
kind: Service
metadata:
  name: lab-service
spec:
  selector:
    app: lab
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
